delay: 0.04
rows: 6
columns: 50
mqtt_client_id: 'name'
mqtt_username: 'user'
mqtt_password: 'pass'
mqtt_broker_address: 'ip'
mqtt_broker_port: 8883
mqtt_command_topic: 'some/topic'
mqtt_state_topic: 'some/topic'
mqtt_availability_topic: 'some/topic'

default_state:
  state: True
  brightness: 1
  effect: solid
  color: 
    - 255
    - 255
    - 255

# dev options
use_mqtt: true
catch_errors: false
